<?php
declare(strict_types=1);

/**
 * Machine-readable tribe/alliance and diplomacy specification derived from
 * docs/todo/tribes_and_diplomacy.md. Useful for validation, UI copy, or seed data.
 */
class TribesDiplomacySpec
{
    private static array $spec = [
        'tribe_structure' => [
            'creation' => [
                'requirements' => [
                    'minimum_player_level' => 10,
                    'gold_cost' => 50000,
                    'minimum_founding_members' => 3,
                    'founders_must_be_tribeless' => true,
                    'max_distance_between_founders_tiles' => 50,
                    'cooldown_days_after_leaving' => 7,
                ],
                'process_steps' => [
                    'founder_initiates',
                    'select_name',
                    'select_tag',
                    'choose_banner_and_colors',
                    'write_description',
                    'invite_founding_members',
                    'founders_accept_within_48h',
                    'tribe_created_when_all_accept_or_three_confirmed',
                ],
                'naming_rules' => [
                    'name_length' => ['min' => 3, 'max' => 20],
                    'tag_length' => ['min' => 2, 'max' => 5],
                    'allowed_chars' => 'letters, spaces, hyphens, apostrophes',
                    'unique_case_insensitive' => true,
                    'no_profanity' => true,
                    'impersonation_blocked' => true,
                    'rename' => [
                        'name_change_cooldown_days' => 90,
                        'name_change_cost_gold' => 100000,
                    ],
                ],
            ],
            'size_and_scaling' => [
                'membership_limits' => [
                    ['level' => 1, 'max_members' => 10, 'unlock_cost_resources' => 0],
                    ['level' => 2, 'max_members' => 20, 'unlock_cost_resources' => 100000],
                    ['level' => 3, 'max_members' => 30, 'unlock_cost_resources' => 250000],
                    ['level' => 4, 'max_members' => 40, 'unlock_cost_resources' => 500000],
                    ['level' => 5, 'max_members' => 50, 'unlock_cost_resources' => 1000000],
                    ['level' => 6, 'max_members' => 75, 'unlock_cost_resources' => 2500000],
                    ['level' => 7, 'max_members' => 100, 'unlock_cost_resources' => 5000000],
                    ['level' => 8, 'max_members' => 150, 'unlock_cost_resources' => 10000000],
                    ['level' => 9, 'max_members' => 200, 'unlock_cost_resources' => 25000000],
                    ['level' => 10, 'max_members' => 300, 'unlock_cost_resources' => 50000000],
                ],
                'minimum_size' => [
                    'active_minimum_members' => 3,
                    'disband_if_below_minimum_days' => 7,
                    'warnings_at_member_counts' => [5, 4, 3],
                    'founder_can_disband' => true,
                ],
            ],
            'leveling_and_progression' => [
                'xp_gain' => [
                    'member_joins' => 100,
                    'member_level_milestone' => ['min' => 50, 'max' => 500],
                    'successful_defense' => 10,
                    'successful_conquest' => 500,
                    'quest_completion' => ['min' => 100, 'max' => 1000],
                    'event_participation' => ['min' => 500, 'max' => 5000],
                    'territory_control_daily' => 100,
                    'wonder_stage' => 10000,
                ],
                'level_benefits' => [
                    ['level' => 1, 'benefits' => ['Basic tribe features', '10 members', 'Tribe chat']],
                    ['level' => 2, 'benefits' => ['Tribe forum', '20 members', 'Tribe warehouse (100k capacity)']],
                    ['level' => 3, 'benefits' => ['Diplomacy system', '30 members', 'Tribe research (tier 1)']],
                    ['level' => 4, 'benefits' => ['War declarations', '40 members', 'Tribe quests']],
                    ['level' => 5, 'benefits' => ['Mass mail', '50 members', 'Tribe market', 'Shared intel']],
                    ['level' => 6, 'benefits' => ['Territory control', '75 members', 'Tribe research (tier 2)']],
                    ['level' => 7, 'benefits' => ['Tribe city', '100 members', 'Advanced coordination tools']],
                    ['level' => 8, 'benefits' => ['Vassalage system', '150 members', 'Tribe research (tier 3)']],
                    ['level' => 9, 'benefits' => ['Wonder construction', '200 members', 'Legendary features']],
                    ['level' => 10, 'benefits' => ['Server dominance', '300 members', 'All features unlocked']],
                ],
                'prestige' => [
                    'notes' => [
                        'tribes earn prestige via achievements',
                        'prestige unlocks cosmetic and minor bonuses',
                        'partial carryover between seasons',
                        'leaderboard is prestige-based',
                    ],
                    'sources' => [
                        'first_to_level_milestones' => 1000,
                        'win_tribe_wars' => ['min' => 500, 'max' => 5000],
                        'complete_tribe_achievements' => ['min' => 100, 'max' => 10000],
                        'control_strategic_locations_weekly' => 100,
                        'build_wonders' => 50000,
                        'season_ranking' => ['min' => 1000, 'max' => 100000],
                    ],
                ],
            ],
            'identity_features' => [
                'tribe_tag' => [
                    'length' => ['min' => 2, 'max' => 5],
                    'display_format' => '[TAG] PlayerName',
                    'unique_per_server' => true,
                    'change_cost_gold' => 50000,
                    'change_cooldown_days' => 30,
                    'color_change_cost_gold' => 10000,
                ],
                'tribe_banner' => [
                    'shape_options' => 20,
                    'primary_colors' => 50,
                    'secondary_colors' => 50,
                    'symbols' => 100,
                    'border_styles' => 20,
                    'free_change_period_days' => 7,
                    'change_cost_gold' => 25000,
                ],
                'descriptions' => [
                    'public_description_chars' => 1000,
                    'internal_description_chars' => 2000,
                    'recruitment_message_chars' => 500,
                    'suggested_content' => [
                        'goals',
                        'requirements',
                        'activity_expectations',
                        'timezone',
                        'language',
                        'external_links',
                    ],
                ],
                'motto' => [
                    'max_chars' => 50,
                    'cooldown_days' => 7,
                ],
                'anthem' => [
                    'max_chars' => 500,
                    'gameplay_impact' => 'none',
                ],
            ],
        ],
        'roles_and_permissions' => [
            'ranks' => [
                'founder' => [
                    'limit' => 1,
                    'permissions' => [
                        'all_permissions',
                        'disband_tribe',
                        'transfer_founder_status',
                        'promote_demote_anyone',
                        'change_name_tag_banner',
                        'manage_settings',
                        'access_resources',
                        'declare_end_wars',
                        'manage_diplomacy',
                        'kick_any_member',
                    ],
                    'responsibilities' => [
                        'ultimate_decision',
                        'long_term_strategy',
                        'conflict_resolution',
                        'major_diplomacy',
                        'tribe_survival_and_growth',
                    ],
                    'activities' => [
                        'strategic_planning',
                        'leadership_management',
                        'crisis_management',
                        'server_level_diplomacy',
                        'community_building',
                    ],
                ],
                'leader' => [
                    'limit' => 5,
                    'permissions' => [
                        'promote_demote_except_founder_and_leaders',
                        'kick_except_founder_and_leaders',
                        'manage_settings_except_name_tag',
                        'warehouse_full_access',
                        'declare_end_wars_with_founder_approval',
                        'manage_diplomacy',
                        'edit_descriptions',
                        'manage_quests',
                        'coordination_tools',
                        'view_activity_logs',
                    ],
                    'responsibilities' => [
                        'day_to_day_management',
                        'leadership_coordination',
                        'decision_implementation',
                        'member_conflict_resolution',
                        'strategic_support',
                    ],
                    'activities' => [
                        'member_management',
                        'conflict_mediation',
                        'resource_allocation',
                        'event_organization',
                    ],
                ],
                'war_officer' => [
                    'limit' => 10,
                    'permissions' => [
                        'create_attack_plans',
                        'assign_targets',
                        'schedule_operations',
                        'view_military_reports',
                        'mass_mail_military',
                        'manage_war_room',
                        'request_reinforcements',
                        'coordinate_defenses',
                        'access_military_stats',
                        'mark_priority_targets',
                    ],
                    'responsibilities' => [
                        'military_strategy',
                        'coordinated_attacks',
                        'defense_coordination',
                        'target_selection',
                        'battle_analysis',
                    ],
                    'activities' => [
                        'planning_offensives',
                        'organizing_defense',
                        'analyzing_enemy_positions',
                        'coordinating_timing',
                        'training_members',
                    ],
                ],
                'diplomat' => [
                    'limit' => 5,
                    'permissions' => [
                        'propose_relations',
                        'communicate_with_diplomats',
                        'view_diplomatic_history',
                        'access_diplomatic_reports',
                        'send_diplomatic_messages',
                        'negotiate_treaties',
                        'manage_naps',
                        'view_public_enemy_info',
                    ],
                    'responsibilities' => [
                        'inter_tribe_relations',
                        'treaty_negotiations',
                        'conflict_deescalation',
                        'alliance_management',
                        'diplomatic_intel',
                    ],
                    'activities' => [
                        'negotiating_alliances',
                        'maintaining_relations',
                        'resolving_conflicts',
                        'gathering_political_intel',
                        'representing_tribe',
                    ],
                ],
                'recruiter' => [
                    'limit' => 10,
                    'permissions' => [
                        'accept_reject_applications',
                        'invite_players',
                        'manage_recruitment_messages',
                        'view_applicant_info',
                        'send_recruitment_mail',
                        'access_recruitment_stats',
                        'promote_recruits',
                        'kick_recruits',
                    ],
                    'responsibilities' => [
                        'grow_membership',
                        'vet_applicants',
                        'onboard_new_members',
                        'maintain_standards',
                        'early_retention',
                    ],
                    'activities' => [
                        'reviewing_applications',
                        'interviewing_candidates',
                        'sending_invitations',
                        'welcoming_new_members',
                        'teaching_systems',
                    ],
                ],
                'logistics_officer' => [
                    'limit' => 10,
                    'permissions' => [
                        'manage_warehouse',
                        'approve_resource_requests',
                        'organize_distribution',
                        'view_contributions',
                        'create_collection_drives',
                        'manage_market',
                        'coordinate_trade_routes',
                        'track_economy',
                        'access_economic_stats',
                    ],
                    'responsibilities' => [
                        'resource_management',
                        'supply_distribution',
                        'economic_planning',
                        'support_military_ops',
                        'member_support',
                    ],
                    'activities' => [
                        'distributing_resources',
                        'organizing_drives',
                        'supporting_new_members',
                        'economic_analysis',
                    ],
                ],
                'intelligence_officer' => [
                    'limit' => 5,
                    'permissions' => [
                        'access_intel_reports',
                        'mark_enemy_villages',
                        'create_intel_briefings',
                        'view_all_scout_reports',
                        'manage_target_database',
                        'track_enemy_movements',
                        'coordinate_recon',
                        'access_spy_reports',
                    ],
                    'responsibilities' => [
                        'information_gathering',
                        'enemy_analysis',
                        'target_identification',
                        'intel_sharing',
                        'threat_assessment',
                    ],
                    'activities' => [
                        'scouting_enemy',
                        'analyzing_strength',
                        'identifying_targets',
                        'tracking_activity',
                        'creating_reports',
                    ],
                ],
                'event_coordinator' => [
                    'limit' => 5,
                    'permissions' => [
                        'create_events',
                        'schedule_activities',
                        'manage_calendar',
                        'send_announcements',
                        'track_participation',
                        'distribute_rewards',
                        'access_event_stats',
                    ],
                    'responsibilities' => [
                        'organize_activities',
                        'event_planning',
                        'member_engagement',
                        'community_building',
                        'morale',
                    ],
                    'activities' => [
                        'planning_events',
                        'organizing_competitions',
                        'coordinating_social',
                        'managing_celebrations',
                        'boosting_morale',
                    ],
                ],
                'member' => [
                    'limit' => 'unlimited',
                    'permissions' => [
                        'tribe_chat',
                        'view_forum_member_sections',
                        'participate_activities',
                        'request_resources',
                        'view_basic_stats',
                        'contribute_projects',
                        'participate_votes',
                        'view_member_list',
                        'access_guides',
                    ],
                    'responsibilities' => [
                        'active_participation',
                        'follow_rules',
                        'contribute_goals',
                        'support_members',
                        'represent_tribe',
                    ],
                    'activities' => [
                        'daily_gameplay',
                        'participating_operations',
                        'contributing_resources',
                        'helping_members',
                        'following_strategy',
                    ],
                ],
                'recruit' => [
                    'limit' => 'unlimited',
                    'permissions' => [
                        'limited_chat',
                        'view_forum_public',
                        'view_description',
                        'view_member_list_limited',
                        'limited_activity_participation',
                    ],
                    'restrictions' => [
                        'no_warehouse',
                        'no_sensitive_info',
                        'no_votes',
                        'no_coordination_tools',
                        'limited_forum_access',
                    ],
                    'trial_period' => [
                        'days_default' => 7,
                        'configurable_min' => 3,
                        'configurable_max' => 30,
                        'auto_promotion_optional' => true,
                        'manual_promotion_by' => ['recruiter', 'higher'],
                        'kick_no_cooldown' => true,
                    ],
                    'responsibilities' => [
                        'prove_activity',
                        'learn_culture',
                        'follow_rules',
                        'demonstrate_value',
                        'build_trust',
                    ],
                ],
            ],
            'permission_matrix' => [
                'disband_tribe' => ['roles' => ['founder']],
                'transfer_founder' => ['roles' => ['founder']],
                'change_name_tag' => ['roles' => ['founder']],
                'promote_demote' => [
                    'roles' => ['founder', 'leader', 'recruiter'],
                    'notes' => [
                        'leaders_cannot_affect_founder_or_leaders',
                        'recruiters_only_on_recruits',
                    ],
                ],
                'kick_members' => [
                    'roles' => ['founder', 'leader', 'recruiter'],
                    'notes' => [
                        'leaders_cannot_affect_founder_or_leaders',
                        'recruiters_only_on_recruits',
                    ],
                ],
                'declare_war' => [
                    'roles' => ['founder', 'leader'],
                    'notes' => ['leaders_need_founder_approval'],
                ],
                'manage_diplomacy' => ['roles' => ['founder', 'leader', 'diplomat']],
                'attack_planning' => ['roles' => ['founder', 'leader', 'war_officer']],
                'mass_mail' => ['roles' => ['founder', 'leader', 'war_officer', 'recruiter', 'event_coordinator']],
                'warehouse_full' => ['roles' => ['founder', 'leader', 'logistics_officer']],
                'warehouse_request' => [
                    'roles' => ['founder', 'leader', 'war_officer', 'diplomat', 'recruiter', 'logistics_officer', 'intelligence_officer', 'event_coordinator', 'member'],
                    'notes' => ['recruits_cannot_request'],
                ],
                'intel_access' => ['roles' => ['founder', 'leader', 'war_officer', 'diplomat', 'intelligence_officer']],
                'forum_all' => ['roles' => ['founder', 'leader', 'war_officer', 'diplomat', 'recruiter', 'logistics_officer', 'intelligence_officer', 'event_coordinator']],
                'forum_member' => ['roles' => ['founder', 'leader', 'war_officer', 'diplomat', 'recruiter', 'logistics_officer', 'intelligence_officer', 'event_coordinator', 'member']],
                'forum_public' => ['roles' => ['founder', 'leader', 'war_officer', 'diplomat', 'recruiter', 'logistics_officer', 'intelligence_officer', 'event_coordinator', 'member', 'recruit']],
                'tribe_chat' => [
                    'roles' => ['founder', 'leader', 'war_officer', 'diplomat', 'recruiter', 'logistics_officer', 'intelligence_officer', 'event_coordinator', 'member', 'recruit'],
                    'notes' => ['recruits_may_be_read_only'],
                ],
            ],
            'custom_ranks' => [
                'max_custom_ranks' => 5,
                'placement' => 'between_predefined_ranks',
                'permission_pool_assignable' => true,
                'member_limit_optional' => true,
                'fields' => [
                    'name_max_chars' => 20,
                    'color_customizable' => true,
                    'description_chars' => 200,
                ],
                'examples' => ['Elite Squad', 'Farmers', 'Night Crew', 'Mentors'],
            ],
        ],
        'tribe_features' => [
            'internal_communication' => [
                'tribe_chat' => [
                    'channels' => [
                        'general',
                        'strategy',
                        'war_room',
                        'leadership',
                        'recruitment',
                        'trade',
                        'custom_channels_up_to_5',
                    ],
                    'features' => [
                        'real_time_messaging',
                        'message_history_7_days_general',
                        'message_history_30_days_leadership',
                        'mentions',
                        'emojis_reactions',
                        'link_previews',
                        'image_sharing_premium',
                        'edit_window_minutes' => 5,
                        'delete_message_by_sender_or_officer',
                        'mute_unmute_channels',
                        'notifications_per_channel',
                    ],
                    'moderation' => [
                        'officers_can_delete',
                        'officers_can_mute_1h_to_7d',
                        'leaders_can_ban_chat',
                        'optional_profanity_filter',
                        'report_system_for_messages',
                    ],
                ],
                'tribe_forum' => [
                    'sections' => [
                        'announcements',
                        'general',
                        'strategy_and_tactics',
                        'recruitment',
                        'war_reports',
                        'leadership',
                        'archives',
                        'custom_sections_up_to_10',
                    ],
                    'features' => [
                        'threads_and_replies',
                        'sticky_threads',
                        'locked_threads',
                        'thread_tags',
                        'search',
                        'subscriptions',
                        'quote_reply',
                        'rich_text',
                        'attachments',
                        'polls',
                        'thread_ratings',
                    ],
                ],
                'announcements' => [
                    'types' => ['critical', 'important', 'normal', 'info'],
                    'fields' => [
                        'title_chars' => 100,
                        'body_chars' => 2000,
                        'expiration',
                        'target_audience',
                        'ack_required',
                        'pin_to_top',
                        'schedule_posting',
                    ],
                    'tracking' => [
                        'view_count',
                        'read_status',
                        'ack_list',
                        'reminders_for_unread',
                    ],
                ],
                'member_notes' => [
                    'personal_notes' => [
                        'visibility' => 'creator_only',
                        'chars' => 500,
                        'searchable' => true,
                    ],
                    'officer_notes' => [
                        'visibility' => 'officers',
                        'chars' => 1000,
                        'timestamped' => true,
                        'searchable' => true,
                    ],
                    'tribe_notes' => [
                        'visibility' => 'all_members',
                        'chars' => 500,
                        'shown_on_profile' => true,
                    ],
                ],
            ],
            'shared_intelligence' => [
                'scout_reports' => [
                    'automatic_sharing' => true,
                    'visibility' => 'intelligence_officers_plus',
                    'filters' => ['player', 'tribe', 'village_type', 'date', 'distance'],
                    'export_csv_premium' => true,
                    'fields' => [
                        'village_details',
                        'units',
                        'resources',
                        'timestamp',
                        'sender',
                        'notes_and_tags',
                        'bookmarks',
                        'compare_over_time',
                    ],
                ],
                'target_database' => [
                    'target_management' => [
                        'priority_levels' => ['high', 'medium', 'low'],
                        'assign_targets',
                        'status_tracking' => ['scouted', 'attacked', 'conquered', 'abandoned'],
                        'target_notes',
                        'target_history',
                        'claim_system',
                    ],
                    'target_lists' => [
                        'named_lists',
                        'share_lists',
                        'assign_to_squads',
                        'track_completion',
                        'auto_update_from_scouts',
                    ],
                ],
                'enemy_tribe_tracking' => [
                    'data' => [
                        'member_list_public',
                        'village_locations_from_scouts',
                        'diplomatic_relations',
                        'tribe_stats_public',
                        'war_history',
                        'notable_members',
                        'activity_patterns',
                    ],
                    'intelligence_reports' => [
                        'officer_briefings',
                        'strength_strategy_vulnerabilities',
                        'sharing_scopes' => ['all_members', 'ranks'],
                        'historical_archive',
                    ],
                ],
            ],
            'research_and_technology' => [
                'economic' => [
                    ['key' => 'shared_prosperity', 'tiers' => [1, 2, 3], 'effect' => '+5/10/15% production'],
                    ['key' => 'trade_network', 'tiers' => [1, 2, 3], 'effect' => '-5/10/15% market fees'],
                    ['key' => 'resource_pooling', 'tiers' => [1], 'effect' => 'enable tribe warehouse'],
                    ['key' => 'bulk_discounts', 'tiers' => [1, 2], 'effect' => '-5/10% building costs'],
                    ['key' => 'collective_bargaining', 'tiers' => [1], 'effect' => 'better NPC trade rates'],
                ],
                'military' => [
                    ['key' => 'united_defense', 'tiers' => [1, 2, 3], 'effect' => '+5/10/15% defense when reinforcing members'],
                    ['key' => 'coordinated_assault', 'tiers' => [1, 2, 3], 'effect' => '+5/10/15% attack in coordinated ops'],
                    ['key' => 'rapid_response', 'tiers' => [1, 2], 'effect' => '+10/20% reinforcement speed'],
                    ['key' => 'shared_intelligence', 'tiers' => [1], 'effect' => 'auto-share scout reports'],
                    ['key' => 'war_machine', 'tiers' => [1, 2, 3], 'effect' => '+5/10/15% unit training speed'],
                ],
                'diplomatic' => [
                    ['key' => 'diplomacy', 'tiers' => [1, 2, 3], 'effect' => 'ally slots 2/4/6'],
                    ['key' => 'non_aggression_pacts', 'tiers' => [1], 'effect' => 'enable NAPs'],
                    ['key' => 'vassalage_system', 'tiers' => [1], 'effect' => 'enable vassal/protectorate'],
                    ['key' => 'trade_agreements', 'tiers' => [1], 'effect' => 'trade bonuses with allies'],
                    ['key' => 'espionage', 'tiers' => [1], 'effect' => 'unlock spy units and sabotage'],
                ],
                'special' => [
                    ['key' => 'tribe_city', 'tiers' => [1], 'effect' => 'unlock tribe city'],
                    ['key' => 'wonder_construction', 'tiers' => [1], 'effect' => 'enable wonders'],
                    ['key' => 'legendary_units', 'tiers' => [1], 'effect' => 'special tribe-only units'],
                    ['key' => 'rituals', 'tiers' => [1], 'effect' => 'tribe-wide rituals and blessings'],
                    ['key' => 'territory_control', 'tiers' => [1], 'effect' => 'enable region control'],
                ],
                'costs' => [
                    'tier_1' => ['resources' => 500000, 'gold' => 50000, 'days' => 7],
                    'tier_2' => ['resources' => 2000000, 'gold' => 200000, 'days' => 14],
                    'tier_3' => ['resources' => 10000000, 'gold' => 1000000, 'days' => 30],
                    'legendary' => ['resources' => 50000000, 'gold' => 5000000, 'gems' => 100, 'days' => 60],
                ],
                'mechanics' => [
                    'all_members_contribute' => true,
                    'progress_tracking_with_leaderboard' => true,
                    'queue_multiple_research' => true,
                    'premium_acceleration' => true,
                    'benefits_apply_immediately' => true,
                ],
            ],
            'tribe_warehouse' => [
                'storage' => [
                    'capacity_formula' => '100k per tribe level',
                    'separate_resources' => true,
                    'gold_storage_formula' => '10k per tribe level',
                    'special_resources_formula' => '100 per tribe level',
                ],
                'contribution' => [
                    'deposit_unrestricted' => true,
                    'withdrawal_requires_permission' => true,
                    'tracking' => ['lifetime', 'monthly'],
                    'leaderboard' => true,
                    'rewards' => true,
                ],
                'request_system' => [
                    'members_can_request' => true,
                    'visible_to_logistics' => true,
                    'approve_deny_with_notes' => true,
                    'daily_request_limit' => 10000,
                    'history_tracked' => true,
                    'auto_approval_trusted' => true,
                ],
                'distribution' => [
                    'bulk_distribution' => true,
                    'purpose_tags' => ['attack', 'defense', 'building'],
                    'tracking' => true,
                    'monthly_reports' => true,
                ],
                'emergency' => [
                    'emergency_withdrawals' => true,
                    'auto_distribution_when_under_attack' => true,
                    'emergency_reserves' => true,
                    'protocols_defined_by_leadership' => true,
                ],
            ],
            'tribe_market' => [
                'internal_trading' => [
                    'fee' => 0,
                    'instant_within_territory' => true,
                    'bulk_orders' => true,
                    'standing_orders' => true,
                    'trade_history' => true,
                ],
                'resource_requests' => [
                    'request_board_visible' => true,
                    'member_fulfillment' => true,
                    'reputation_system' => true,
                ],
                'tribe_merchant' => [
                    'npc_better_rates' => true,
                    'rates_scale_with_level' => true,
                    'limited_stock_daily' => true,
                    'exclusive_items' => true,
                    'bulk_discounts' => true,
                ],
            ],
            'tribe_quests' => [
                'daily' => [
                    ['name' => 'Contribute 10k resources to warehouse', 'reward' => '5k mixed resources'],
                    ['name' => 'Complete 5 attacks on enemy tribe', 'reward' => '10k mixed resources, 500 gold'],
                    ['name' => 'Defend 3 tribe member villages', 'reward' => '8k mixed resources'],
                    ['name' => 'Scout 10 enemy villages', 'reward' => '5k gold'],
                    ['name' => 'Complete 5 trades with tribe members', 'reward' => '3k gold'],
                ],
                'weekly' => [
                    ['name' => 'Tribe contributes 500k total resources', 'reward' => '50k mixed, 5k gold to all'],
                    ['name' => 'Win 50 battles against enemy tribe', 'reward' => '100k mixed, 10k gold'],
                    ['name' => 'Control 5 map objectives', 'reward' => '200k mixed, 20k gold, 5 gems'],
                    ['name' => 'Complete 100 trades', 'reward' => '50k gold'],
                    ['name' => 'Recruit 10 new members', 'reward' => '100k mixed'],
                ],
                'seasonal' => [
                    ['name' => 'Build a Wonder', 'reward' => '1M mixed, 100k gold, 100 gems, legendary title'],
                    ['name' => 'Win Tribe War Season', 'reward' => '500k mixed, 50k gold, 50 gems'],
                    ['name' => 'Control 20% of server', 'reward' => '2M mixed, 200k gold, 200 gems'],
                    ['name' => 'Reach tribe level 10', 'reward' => '1M mixed, 100k gold, prestige'],
                    ['name' => 'Complete 100 tribe achievements', 'reward' => 'legendary banner, 500k gold'],
                ],
                'reward_rules' => [
                    'distributed_to_active_members',
                    'contribution_scaling',
                    'bonus_for_leaders',
                    'tracked_in_statistics',
                ],
            ],
            'tribe_achievements' => [
                'membership' => [
                    'Growing Family' => [10, 25, 50, 100, 200],
                    'Loyal Tribe' => '50% members active 30+ days',
                    'Elite Tribe' => 'average member level 50+',
                    'Veteran Tribe' => [90, 180, 365],
                ],
                'economic' => [
                    'Resource Hoarders' => [10000000, 50000000, 100000000],
                    'Trade Empire' => [1000, 5000, 10000],
                    'Wealthy Tribe' => [100000000, 500000000, 1000000000],
                    'Generous Tribe' => [50000000, 200000000, 500000000],
                ],
                'military' => [
                    'Conquerors' => [10, 50, 100, 500],
                    'Defenders' => [100, 500, 1000],
                    'Warriors' => [1000, 5000, 10000],
                    'Dominators' => [10, 25, 50],
                ],
                'diplomatic' => [
                    'Peaceful Tribe' => 'maintain 5 alliances for 30 days',
                    'Warmongers' => [5, 10, 20],
                    'Diplomatic Masters' => [10, 25, 50],
                    'Server Power' => 'top 10 for 30/60/90 days',
                ],
                'special' => [
                    'Wonder Builders',
                    'Legendary Tribe',
                    'Server Champions',
                    'Immortal Tribe',
                ],
                'rewards' => [
                    'prestige',
                    'cosmetics',
                    'small_gameplay_bonuses',
                    'leaderboard_recognition',
                    'hall_of_fame',
                ],
            ],
        ],
        'diplomacy_states' => [
            'neutral' => [
                'gameplay_effects' => [
                    'attacks_allowed',
                    'no_shared_information',
                    'no_trade_bonuses',
                    'no_map_coloring',
                    'no_coordination_tools',
                ],
                'transition' => [
                    'default_state',
                    'returns_when_relations_end',
                    'no_cost',
                ],
            ],
            'ally' => [
                'gameplay_effects' => [
                    'attack_blocked',
                    'shared_intelligence',
                    'reinforcement_bonus_10_percent',
                    'map_coloring' => 'green',
                    'trade_fee_reduction_50_percent',
                    'shared_attack_planner',
                    'shared_ally_chat',
                    'ally_forum_public_view',
                    'warehouse_request_with_approval',
                    'optional_auto_join_wars',
                ],
                'requirements' => [
                    'mutual_acceptance',
                    'tribe_level_min' => 3,
                    'not_at_war',
                    'ally_slots' => ['min' => 2, 'max' => 6],
                    'cooldown_after_end_days' => 7,
                ],
                'costs' => [
                    'proposal_gold' => 10000,
                    'maintenance_gold_weekly' => 5000,
                    'break_cost_gold' => 50000,
                    'reputation_penalty_on_break' => true,
                ],
                'duration' => [
                    'indefinite' => true,
                    'notice_period_days' => 7,
                    'emergency_cancel_cost_gold' => 100000,
                ],
                'alliance_levels' => [
                    'basic',
                    'strong' => '+5% bonuses after 30 days',
                    'legendary' => '+10% bonuses after 90 days',
                ],
            ],
            'nap' => [
                'gameplay_effects' => [
                    'attack_warning_with_override',
                    'reputation_penalty_on_break',
                    'map_coloring' => 'blue',
                    'trade_fee_reduction_25_percent',
                    'shared_diplomatic_chat',
                    'limited_intel_sharing_opt_in',
                    'no_reinforcement',
                    'no_coordination_tools',
                ],
                'requirements' => [
                    'mutual_acceptance',
                    'tribe_level_min' => 2,
                    'not_at_war',
                    'nap_slots' => 'unlimited',
                    'cooldown_after_end_days' => 3,
                ],
                'costs' => [
                    'proposal_gold' => 5000,
                    'maintenance_gold_weekly' => 1000,
                    'break_cost_gold' => 25000,
                    'major_reputation_penalty_on_break' => true,
                ],
                'duration' => [
                    'minimum_days' => 7,
                    'maximum' => 'indefinite',
                    'notice_period_days' => 3,
                    'auto_renewal_default' => true,
                ],
            ],
            'enemy' => [
                'gameplay_effects' => [
                    'attack_bonus_5_percent',
                    'map_coloring' => 'red',
                    'war_statistics',
                    'war_leaderboard',
                    'war_room',
                    'priority_targets',
                    'no_trade',
                    'reputation_gain_for_victories',
                    'war_rewards',
                    'server_notification_on_declaration',
                ],
                'requirements' => [
                    'tribe_level_min' => 4,
                    'founder_or_leader_approval',
                    'not_allied',
                    'declaration_period_hours' => 24,
                    'declaration_cost_gold' => 50000,
                ],
                'duration' => [
                    'minimum_days' => 7,
                    'maximum' => 'indefinite',
                    'peace_treaty_required_to_end' => true,
                    'surrender_option' => true,
                ],
                'war_phases' => ['declaration', 'active_war', 'peace_negotiation', 'ceasefire'],
            ],
            'vassalage' => [
                'vassal' => [
                    'description' => 'subordinate tribe under overlord protection',
                    'tribute_percent_production' => 10,
                    'protection' => true,
                    'limited_autonomy' => true,
                    'shared_intelligence_partial' => true,
                    'map_coloring' => 'light_purple',
                ],
                'protectorate' => [
                    'description' => 'protected tribe with more autonomy',
                    'tribute_percent_production' => 5,
                    'military_support' => true,
                    'full_diplomatic_autonomy' => true,
                    'map_coloring' => 'light_blue',
                ],
                'requirements' => [
                    'tribe_level_min' => 8,
                    'power_difference_min_multiplier' => 3,
                    'mutual_agreement_or_conquest',
                    'vassal_slots_max' => 3,
                ],
                'benefits' => [
                    'overlord_resources',
                    'expanded_influence',
                    'vassal_protection',
                    'growth_opportunity',
                ],
                'release_and_rebellion' => [
                    'overlord_can_release' => true,
                    'vassal_can_request_release' => true,
                    'vassal_can_rebel' => true,
                    'rebellion_triggers_war' => true,
                    'failure_penalties' => 'harsher tribute',
                ],
            ],
        ],
        'war_and_peace_mechanics' => [
            'war_declaration' => [
                'process' => [
                    'leader_proposes',
                    'leadership_vote_optional',
                    'founder_or_leader_approval',
                    'pay_cost_50000_gold',
                    '24h_warning_sent',
                    'preparation_period',
                    'war_begins_and_announced',
                ],
                'requirements' => [
                    'tribe_level_min' => 4,
                    'not_allied_with_target',
                    'sufficient_gold',
                    'cooldown_days_since_last_war' => 7,
                    'target_min_members' => 5,
                ],
                'casus_belli' => [
                    'justified_cost_gold' => 25000,
                    'unjustified_cost_gold' => 100000,
                    'types' => [
                        'territory_dispute',
                        'treaty_violation',
                        'revenge',
                        'resource_competition',
                        'ideological',
                    ],
                    'reputation_adjusts' => true,
                ],
            ],
            'war_statistics' => [
                'individual' => [
                    'attacks_launched',
                    'attack_success_rate',
                    'defenses',
                    'defense_success_rate',
                    'resources_looted',
                    'units_killed',
                    'units_lost',
                    'villages_conquered',
                    'villages_lost',
                    'war_points',
                ],
                'tribe' => [
                    'total_attacks',
                    'total_defenses',
                    'net_resources',
                    'net_units',
                    'territory_gained_lost',
                    'war_score',
                    'participation_rate',
                ],
                'war_score_formula' => '(resources_looted * 0.1) + (enemy_units_killed * 10) + (villages_conquered * 10000) + (successful_defenses * 500) - (own_units_lost * 5) - (villages_lost * 5000)',
                'real_time_tracking' => [
                    'live_dashboard',
                    'recent_battles_feed',
                    'top_contributors',
                    'progress_indicators',
                    'victory_defeat_predictions',
                ],
            ],
            'war_leaderboards' => [
                'individual' => [
                    'most_resources_looted',
                    'most_units_killed',
                    'most_villages_conquered',
                    'best_attack_success_rate',
                    'best_defense_success_rate',
                    'highest_war_points',
                    'most_active',
                ],
                'tribe' => [
                    'highest_war_score',
                    'most_wars_won',
                    'longest_winning_streak',
                    'most_villages_conquered_all_time',
                    'most_resources_looted_all_time',
                    'best_war_record',
                ],
                'rewards' => [
                    'top_10_individuals' => 'gold_gems_titles',
                    'top_3_tribes' => 'resources_prestige_cosmetics',
                    'participation_rewards' => true,
                    'victory_bonus_multiplier' => 2,
                ],
            ],
            'peace_and_treaties' => [
                'peace_proposal' => [
                    'either_side_can_propose',
                    'terms_can_include' => ['reparations', 'territory', 'nap_duration', 'tribute', 'apology'],
                    'accept_reject_counter' => true,
                    'negotiation_period_days' => 7,
                ],
                'treaty_terms' => [
                    'white_peace',
                    'conditional',
                    'tribute_peace',
                    'territory_peace',
                    'nap_peace',
                    'reparations_peace',
                ],
                'enforcement' => [
                    'auto_resource_transfers',
                    'village_transfers_manual',
                    'nap_auto_applied',
                    'violation_tracking',
                    'penalties_for_violation',
                ],
                'ceasefire' => [
                    'duration_hours_min' => 24,
                    'duration_hours_max' => 72,
                    'extensions_allowed',
                    'violations_hit_reputation',
                    'auto_end_if_no_peace',
                ],
            ],
            'surrender_mechanics' => [
                'unconditional' => [
                    'winner_dictates_terms',
                    'typical_terms' => [
                        '50_percent_resources',
                        '3_to_10_villages',
                        '90_day_nap',
                        'possible_vassalage',
                        'public_apology',
                    ],
                    'reputation' => ['loser' => 'major_loss', 'winner' => 'major_gain'],
                ],
                'conditional' => [
                    'loser_proposes_limits',
                    'typical_terms' => [
                        '25_percent_resources',
                        '1_to_5_villages',
                        '60_day_nap',
                        'mutual_respect_clause',
                    ],
                    'reputation' => ['loser' => 'moderate_loss', 'winner' => 'moderate_gain'],
                ],
                'process' => [
                    'loser_proposes',
                    'terms_negotiated',
                    'winner_accepts',
                    '24h_implementation',
                    'auto_execute_terms',
                    'war_ends_and_announced',
                ],
                'protections' => [
                    'cannot_be_forced',
                    'can_reject_demands',
                    'can_continue_fighting',
                    'always_voluntary',
                ],
            ],
            'war_consequences' => [
                'winner_rewards' => [
                    'war_chest_percent' => 10,
                    'prestige_range' => [5000, 50000],
                    'titles' => true,
                    'cosmetics' => true,
                    'territory_retained' => true,
                    'reputation_gain_range' => [50, 500],
                ],
                'loser_consequences' => [
                    'resource_loss',
                    'territory_loss',
                    'member_loss',
                    'reputation_loss_range' => [50, 500],
                    'morale_penalty_percent' => 10,
                    'war_cooldown_days' => 14,
                ],
                'stalemate' => [
                    'white_peace',
                    'minimal_consequence',
                    'reputation_neutral_or_slight_loss_for_aggressor',
                ],
                'war_exhaustion' => [
                    'triggers_after_days' => 30,
                    'effects' => [
                        'production_penalty_percent_per_30_days' => 5,
                        'morale_penalty_percent' => 10,
                        'increased_inactivity',
                        'higher_war_action_costs',
                    ],
                    'reduction' => ['rituals', 'events'],
                ],
            ],
        ],
        'coordination_tools' => [
            'mass_mail' => [
                'features' => [
                    'send_to_all_or_ranks',
                    'subject_chars' => 100,
                    'body_chars' => 2000,
                    'attachments',
                    'scheduling',
                    'priority_levels' => ['normal', 'important', 'urgent'],
                    'read_receipts',
                    'reply_options',
                ],
                'permissions' => [
                    'founder_leader_unlimited',
                    'war_officer_limit_per_day' => 5,
                    'recruiter_limit_per_day' => 3,
                    'event_coordinator_limit_per_day' => 3,
                    'members_cannot_send' => true,
                ],
                'templates' => [
                    'war_declaration',
                    'attack_coordination',
                    'defense_call',
                    'resource_request',
                    'event_announcement',
                    'recruitment_drive',
                    'policy_change',
                    'celebration',
                ],
                'anti_spam' => [
                    'rate_limit_per_day' => 10,
                    'member_opt_out',
                    'report_spam',
                    'duplicate_filtering',
                ],
            ],
            'alerts_and_pings' => [
                'alert_types' => [
                    'under_attack',
                    'reinforcement_needed',
                    'target_spotted',
                    'operation_starting',
                    'war_declaration',
                    'peace_offer',
                    'resource_request',
                    'achievement_unlocked',
                ],
                'delivery' => [
                    'in_game_notification',
                    'browser_notification',
                    'email',
                    'mobile_push',
                    'sound_alert',
                    'chat_message',
                ],
                'settings' => [
                    'per_alert_customization',
                    'quiet_hours',
                    'priority_filtering',
                    'cooldown_minutes' => 5,
                    'custom_keywords',
                ],
                'ping_system' => [
                    '@mention_member',
                    '@role',
                    '@online',
                    '@all_officer_restricted',
                    '@here',
                ],
                'emergency_ping' => [
                    'red_alert',
                    'bypasses_quiet_hours',
                    'limit_per_day' => 1,
                    'requires_founder_or_leader',
                    'examples' => [
                        'massive_attack',
                        'wonder_under_threat',
                    ],
                ],
            ],
            'scheduled_operations' => [
                'operation_planner' => [
                    'named_operations',
                    'datetime',
                    'assign_participants',
                    'define_objectives',
                    'attach_strategy',
                    'reminders' => ['24h', '12h', '1h', '15m'],
                    'track_participation',
                ],
                'operation_types' => [
                    'coordinated_attack',
                    'wave_attack',
                    'defensive_operation',
                    'conquest_operation',
                    'raid_operation',
                    'siege_operation',
                ],
                'features' => [
                    'countdown_timer',
                    'participant_lists',
                    'target_details',
                    'attack_simulator',
                    'operation_chat',
                    'post_operation_report',
                ],
                'templates' => [
                    'save_successful_operations',
                    'reuse_templates',
                    'share_templates',
                    'import_with_permission',
                ],
            ],
            'target_lists' => [
                'creation' => [
                    'named_lists',
                    'add_targets',
                    'priority' => ['high', 'medium', 'low'],
                    'notes',
                    'status' => ['available', 'claimed', 'completed', 'abandoned'],
                    'share_with_members_or_all',
                ],
            ],
        ],
    ];

    public static function all(): array
    {
        return self::$spec;
    }

    public static function section(string $path): array
    {
        $segments = array_filter(explode('.', $path), 'strlen');
        $cursor = self::$spec;
        foreach ($segments as $segment) {
            if (!is_array($cursor) || !array_key_exists($segment, $cursor)) {
                return [];
            }
            $cursor = $cursor[$segment];
        }
        return is_array($cursor) ? $cursor : [];
    }
}
